
name: attendance_app
description: A Flutter app for attendance with Firebase and biometrics.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  local_auth: ^2.1.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png" # ← Ito ang app icon mo
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png # ← Ito ang splash screen image mo
  android: true
  ios: false
