name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # or your desired version

      - name: Install dependencies
        run: |
          cd mmarjun002
          flutter pub get

      - name: Build release APK
        run: |
          cd mmarjun002
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: mmarjun002/build/app/outputs/flutter-apk/app-release.apk
